# Generated by scripts/chain_defaults/generate.js -- do not edit.
"""Default chain endpoint tables."""

from typing import List

UNKNOWN_CHAIN_PROVER_FALLBACK = ["https://c4.incubed.net"]

_PROVERS = {
    1: [
        "https://mainnet.colibri-proof.tech",
        "https://mainnet1.colibri-proof.tech",
        "https://mainnet-prover.incubed.net",
        "https://mainnet.colimind.com",
    ],  # mainnet
    11155111: [
        "https://sepolia.colibri-proof.tech",
        "https://sepolia1.colibri-proof.tech",
    ],  # sepolia
    100: [
        "https://gnosis.colibri-proof.tech",
        "https://gnosis1.colibri-proof.tech",
    ],  # gnosis
    10200: ["https://chiado.colibri-proof.tech"],  # chiado
    7091047534: ["https://plataberget.colibri-proof.tech"],  # plataberget
}

_ETH_RPCS = {
    1: [
        "https://mainnet.colibri-proof.tech/execution",
        "https://eth.drpc.org",
        "https://ethereum-rpc.publicnode.com",
        "https://singapore.rpc.blxrbdn.com",
    ],  # mainnet
    11155111: [
        "https://sepolia.colibri-proof.tech/execution",
        "https://ethereum-sepolia-rpc.publicnode.com",
        "https://sepolia.gateway.tenderly.co",
    ],  # sepolia
    100: [
        "https://gnosis.colibri-proof.tech/execution",
        "https://rpc.gnosischain.com",
        "https://rpc.gnosis.gateway.fm",
        "https://gnosis-rpc.publicnode.com",
    ],  # gnosis
    10200: [
        "https://rpc.chiado.gnosis.gateway.fm",
        "https://rpc.chiadochain.net",
        "https://gnosis-chiado-rpc.publicnode.com",
    ],  # chiado
    7091047534: [
        "https://plataberget.colibri-proof.tech/execution",
        "https://rpc.glamsterdam-devnet-8.ethpandaops.io/",
    ],  # plataberget
}

_BEACON_APIS = {
    1: [
        "https://mainnet.colibri-proof.tech/consensus",
        "https://gateway.tenderly.co/public/mainnet",
        "https://ethereum-beacon-api.publicnode.com",
    ],  # mainnet
    11155111: [
        "https://sepolia.colibri-proof.tech/consensus",
        "https://ethereum-sepolia-beacon-api.publicnode.com",
    ],  # sepolia
    100: [
        "https://gnosis.colibri-proof.tech/consensus",
        "https://rpc-gbc.gnosischain.com",
        "https://gnosis-beacon-api.publicnode.com",
    ],  # gnosis
    10200: ["https://rpc-gbc.chiadochain.net"],  # chiado
    7091047534: [
        "https://plataberget.colibri-proof.tech/consensus",
        "https://beacon.glamsterdam-devnet-8.ethpandaops.io/",
    ],  # plataberget
}

_CHECKPOINTZ = {
    1: [
        "https://sync-mainnet.beaconcha.in",
        "https://mainnet.checkpoint.sigp.io",
        "https://mainnet-checkpoint-sync.attestant.io",
        "https://beaconstate-mainnet.chainsafe.io",
        "https://mainnet-checkpoint-sync.stakely.io",
        "https://checkpointz.pietjepuk.net",
        "https://beaconstate.ethstaker.cc",
    ],  # mainnet
    11155111: [
        "https://checkpoint-sync.sepolia.ethpandaops.io",
        "https://beaconstate-sepolia.chainsafe.io",
    ],  # sepolia
    100: ["https://checkpoint.gnosischain.com"],  # gnosis
    10200: ["https://checkpoint.chiadochain.net"],  # chiado
    7091047534: ["https://checkpoint-sync.glamsterdam-devnet-8.ethpandaops.io"],  # plataberget
}

def default_provers(chain_id: int) -> List[str]:
    return list(_PROVERS.get(chain_id, UNKNOWN_CHAIN_PROVER_FALLBACK))

def default_eth_rpcs(chain_id: int) -> List[str]:
    return list(_ETH_RPCS.get(chain_id, []))

def default_beacon_apis(chain_id: int) -> List[str]:
    return list(_BEACON_APIS.get(chain_id, []))

def default_checkpointz(chain_id: int) -> List[str]:
    return list(_CHECKPOINTZ.get(chain_id, []))
