/* Generated by scripts/chain_defaults/generate.js -- do not edit. */
#ifndef default_chains_generated_h__
#define default_chains_generated_h__

static bool c4_default_chain_id_from_name(const char* name, chain_id_t* out) {
  if (!name || !out) return false;
  if (strcmp(name, "mainnet") == 0 || strcmp(name, "eth") == 0 || strcmp(name, "0x1") == 0) {
    *out = 1ULL;
    return true;
  }
  if (strcmp(name, "sepolia") == 0 || strcmp(name, "0xaa36a7") == 0) {
    *out = 11155111ULL;
    return true;
  }
  if (strcmp(name, "gnosis") == 0 || strcmp(name, "xdai") == 0 || strcmp(name, "0x64") == 0) {
    *out = 100ULL;
    return true;
  }
  if (strcmp(name, "chiado") == 0 || strcmp(name, "0x27d8") == 0) {
    *out = 10200ULL;
    return true;
  }
  if (strcmp(name, "plataberget") == 0 || strcmp(name, "glamsterdam-devnet-8") == 0 || strcmp(name, "0x1a6a8cc6e") == 0) {
    *out = 7091047534ULL;
    return true;
  }
  return false;
}

static const char* c4_default_chain_config_json(chain_id_t chain_id) {
  switch (chain_id) {
    case 1ULL: // mainnet
      return "{\"eth_rpc\":[\"https://mainnet.colibri-proof.tech/execution\",\"https://eth.drpc.org\",\"https://ethereum-rpc.publicnode.com\",\"https://singapore.rpc.blxrbdn.com\"],\"beacon_api\":[\"https://mainnet.colibri-proof.tech/consensus\",\"https://gateway.tenderly.co/public/mainnet\",\"https://ethereum-beacon-api.publicnode.com\"],\"checkpointz\":[\"https://sync-mainnet.beaconcha.in\",\"https://mainnet.checkpoint.sigp.io\",\"https://mainnet-checkpoint-sync.attestant.io\",\"https://beaconstate-mainnet.chainsafe.io\",\"https://mainnet-checkpoint-sync.stakely.io\",\"https://checkpointz.pietjepuk.net\",\"https://beaconstate.ethstaker.cc\"],\"prover\":[\"https://mainnet.colibri-proof.tech\",\"https://mainnet1.colibri-proof.tech\",\"https://mainnet-prover.incubed.net\",\"https://mainnet.colimind.com\"]}";
    case 11155111ULL: // sepolia
      return "{\"eth_rpc\":[\"https://sepolia.colibri-proof.tech/execution\",\"https://ethereum-sepolia-rpc.publicnode.com\",\"https://sepolia.gateway.tenderly.co\"],\"beacon_api\":[\"https://sepolia.colibri-proof.tech/consensus\",\"https://ethereum-sepolia-beacon-api.publicnode.com\"],\"checkpointz\":[\"https://checkpoint-sync.sepolia.ethpandaops.io\",\"https://beaconstate-sepolia.chainsafe.io\"],\"prover\":[\"https://sepolia.colibri-proof.tech\",\"https://sepolia1.colibri-proof.tech\"]}";
    case 100ULL: // gnosis
      return "{\"eth_rpc\":[\"https://gnosis.colibri-proof.tech/execution\",\"https://rpc.gnosischain.com\",\"https://rpc.gnosis.gateway.fm\",\"https://gnosis-rpc.publicnode.com\"],\"beacon_api\":[\"https://gnosis.colibri-proof.tech/consensus\",\"https://rpc-gbc.gnosischain.com\",\"https://gnosis-beacon-api.publicnode.com\"],\"checkpointz\":[\"https://checkpoint.gnosischain.com\"],\"prover\":[\"https://gnosis.colibri-proof.tech\",\"https://gnosis1.colibri-proof.tech\"]}";
    case 10200ULL: // chiado
      return "{\"eth_rpc\":[\"https://rpc.chiado.gnosis.gateway.fm\",\"https://rpc.chiadochain.net\",\"https://gnosis-chiado-rpc.publicnode.com\"],\"beacon_api\":[\"https://rpc-gbc.chiadochain.net\"],\"checkpointz\":[\"https://checkpoint.chiadochain.net\"],\"prover\":[\"https://chiado.colibri-proof.tech\"]}";
    case 7091047534ULL: // plataberget
      return "{\"eth_rpc\":[\"https://plataberget.colibri-proof.tech/execution\"],\"beacon_api\":[\"https://plataberget.colibri-proof.tech/consensus\"],\"checkpointz\":[\"https://checkpoint-sync.glamsterdam-devnet-8.ethpandaops.io\"],\"prover\":[\"https://plataberget.colibri-proof.tech\"]}";
    default:
      return NULL;
  }
}

#endif
