#!/usr/bin/env node
/**
 * Generate per-language default chain endpoint tables from chains.json.
 *
 * Usage:
 *   node scripts/chain_defaults/generate.js
 *   node scripts/chain_defaults/generate.js --check
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '../..');
const SPEC_PATH = path.join(__dirname, 'chains.json');
const CHECK = process.argv.includes('--check');

const RUST_CONST = {
  1: 'MAINNET',
  11155111: 'SEPOLIA',
  100: 'GNOSIS',
  10200: 'CHIADO',
  7091047534: 'PLATABERGET',
};

const RUST_DOC = {
  1: 'Ethereum Mainnet.',
  11155111: 'Ethereum Sepolia testnet.',
  100: 'Gnosis Chain.',
  10200: 'Chiado testnet (Gnosis).',
  7091047534: 'Platåberget (Glamsterdam devnet-8).',
};

function loadSpec() {
  const spec = JSON.parse(fs.readFileSync(SPEC_PATH, 'utf8'));
  if (!Array.isArray(spec.chains) || spec.chains.length === 0) {
    throw new Error('chains.json: missing chains array');
  }
  if (!Array.isArray(spec.unknown_chain_prover_fallback) || spec.unknown_chain_prover_fallback.length === 0) {
    throw new Error('chains.json: missing unknown_chain_prover_fallback');
  }
  const ids = new Set();
  const aliases = new Set();
  for (const chain of spec.chains) {
    for (const key of ['id', 'name', 'aliases', 'eth_rpc', 'beacon_api', 'checkpointz', 'prover', 'pollingInterval']) {
      if (chain[key] === undefined) throw new Error(`chains.json: chain ${chain.name || '?'} missing ${key}`);
    }
    if (typeof chain.id !== 'number' || !Number.isSafeInteger(chain.id) || chain.id <= 0) {
      throw new Error(`chains.json: invalid id on ${chain.name}`);
    }
    if (ids.has(chain.id)) throw new Error(`chains.json: duplicate id ${chain.id}`);
    ids.add(chain.id);
    if (!Array.isArray(chain.aliases) || chain.aliases.length === 0) {
      throw new Error(`chains.json: ${chain.name} aliases must be a non-empty array`);
    }
    for (const alias of chain.aliases) {
      if (aliases.has(alias)) throw new Error(`chains.json: duplicate alias ${alias}`);
      aliases.add(alias);
    }
    for (const field of ['eth_rpc', 'beacon_api', 'checkpointz', 'prover']) {
      if (!Array.isArray(chain[field]) || chain[field].some((u) => typeof u !== 'string' || !u.startsWith('https://'))) {
        throw new Error(`chains.json: ${chain.name}.${field} must be an array of https URLs`);
      }
    }
    if (typeof chain.pollingInterval !== 'number' || chain.pollingInterval <= 0) {
      throw new Error(`chains.json: ${chain.name} pollingInterval must be a positive number`);
    }
  }
  return spec;
}

function rustInt(id) {
  return id.toString().replace(/\B(?=(\d{3})+(?!\d))/g, '_');
}

function cEscape(s) {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function cliConfigJson(chain) {
  return JSON.stringify({
    eth_rpc: chain.eth_rpc,
    beacon_api: chain.beacon_api,
    checkpointz: chain.checkpointz,
    prover: chain.prover,
  });
}

function banner(kind) {
  const comments = {
    c: '/* Generated by scripts/chain_defaults/generate.js -- do not edit. */',
    ts: '/* Generated by scripts/chain_defaults/generate.js -- do not edit. */',
    py: '# Generated by scripts/chain_defaults/generate.js -- do not edit.',
    rs: '//! Generated by `scripts/chain_defaults/generate.js` -- do not edit.',
    dart: '// Generated by scripts/chain_defaults/generate.js -- do not edit.',
    kt: '// Generated by scripts/chain_defaults/generate.js -- do not edit.',
    swift: '// Generated by scripts/chain_defaults/generate.js -- do not edit.',
  };
  return comments[kind] + '\n';
}

function genC(spec) {
  let out = banner('c');
  out += '#ifndef default_chains_generated_h__\n';
  out += '#define default_chains_generated_h__\n\n';
  out += 'static bool c4_default_chain_id_from_name(const char* name, chain_id_t* out) {\n';
  out += '  if (!name || !out) return false;\n';
  for (const chain of spec.chains) {
    const cond = chain.aliases.map((a) => `strcmp(name, "${cEscape(a)}") == 0`).join(' || ');
    out += `  if (${cond}) {\n`;
    out += `    *out = ${chain.id}ULL;\n`;
    out += '    return true;\n';
    out += '  }\n';
  }
  out += '  return false;\n';
  out += '}\n\n';
  out += 'static const char* c4_default_chain_config_json(chain_id_t chain_id) {\n';
  out += '  switch (chain_id) {\n';
  for (const chain of spec.chains) {
    out += `    case ${chain.id}ULL: // ${chain.name}\n`;
    out += `      return "${cEscape(cliConfigJson(chain))}";\n`;
  }
  out += '    default:\n';
  out += '      return NULL;\n';
  out += '  }\n';
  out += '}\n\n';
  out += '#endif\n';
  return out;
}

function genTs(spec) {
  let out = banner('ts');
  out += '\nexport const default_config: {\n';
  out += '  [key: string]: {\n';
  out += '    alias: string[];\n';
  out += '    beacon_apis: string[];\n';
  out += '    rpcs: string[];\n';
  out += '    prover: string[];\n';
  out += '    checkpointz: string[];\n';
  out += '    pollingInterval: number;\n';
  out += '  }\n';
  out += '} = {\n';
  for (const chain of spec.chains) {
    out += `  '${chain.id}': { // ${chain.name}\n`;
    out += `    alias: ${JSON.stringify(chain.aliases)},\n`;
    out += `    rpcs: [\n`;
    for (const u of chain.eth_rpc) out += `      ${JSON.stringify(u)},\n`;
    out += `    ],\n`;
    out += `    beacon_apis: [\n`;
    for (const u of chain.beacon_api) out += `      ${JSON.stringify(u)},\n`;
    out += `    ],\n`;
    out += `    prover: [${chain.prover.map((u) => JSON.stringify(u)).join(', ')}],\n`;
    out += `    checkpointz: [\n`;
    for (const u of chain.checkpointz) out += `      ${JSON.stringify(u)},\n`;
    out += `    ],\n`;
    out += `    pollingInterval: ${chain.pollingInterval},\n`;
    out += `  },\n`;
  }
  out += '};\n';
  return out;
}

function pyList(urls, indentSize) {
  if (urls.length === 1) return `[${JSON.stringify(urls[0])}]`;
  const pad = ' '.repeat(indentSize);
  const inner = urls.map((u) => `${pad}    ${JSON.stringify(u)},`).join('\n');
  return `[\n${inner}\n${pad}]`;
}

function genPy(spec) {
  let out = banner('py');
  out += '"""Default chain endpoint tables."""\n\n';
  out += 'from typing import List\n\n';
  out += `UNKNOWN_CHAIN_PROVER_FALLBACK = ${JSON.stringify(spec.unknown_chain_prover_fallback)}\n\n`;

  const maps = [
    ['_PROVERS', 'prover'],
    ['_ETH_RPCS', 'eth_rpc'],
    ['_BEACON_APIS', 'beacon_api'],
    ['_CHECKPOINTZ', 'checkpointz'],
  ];
  for (const [name, field] of maps) {
    out += `${name} = {\n`;
    for (const chain of spec.chains) {
      out += `    ${chain.id}: ${pyList(chain[field], 4)},  # ${chain.name}\n`;
    }
    out += '}\n\n';
  }

  out += 'def default_provers(chain_id: int) -> List[str]:\n';
  out += '    return list(_PROVERS.get(chain_id, UNKNOWN_CHAIN_PROVER_FALLBACK))\n\n';
  out += 'def default_eth_rpcs(chain_id: int) -> List[str]:\n';
  out += '    return list(_ETH_RPCS.get(chain_id, []))\n\n';
  out += 'def default_beacon_apis(chain_id: int) -> List[str]:\n';
  out += '    return list(_BEACON_APIS.get(chain_id, []))\n\n';
  out += 'def default_checkpointz(chain_id: int) -> List[str]:\n';
  out += '    return list(_CHECKPOINTZ.get(chain_id, []))\n';
  return out;
}

function rustVec(urls) {
  if (urls.length === 0) return 'vec![]';
  if (urls.length === 1) return `vec![${JSON.stringify(urls[0])}.into()]`;
  const inner = urls.map((u) => `            ${JSON.stringify(u)}.into(),`).join('\n');
  return `vec![\n${inner}\n        ]`;
}

function genRs(spec) {
  let out = banner('rs');
  out += '//!\n';
  out += '//! Chain identifiers and default endpoint URLs.\n\n';

  for (const chain of spec.chains) {
    const constName = RUST_CONST[chain.id];
    if (!constName) throw new Error(`No Rust constant name for chain ${chain.id}`);
    out += `/// ${RUST_DOC[chain.id] || chain.name}\n`;
    out += `pub const ${constName}: u64 = ${rustInt(chain.id)};\n`;
  }
  out += '\n';

  const fallback = spec.unknown_chain_prover_fallback.map((u) => `${JSON.stringify(u)}.into()`).join(', ');

  const fns = [
    ['default_provers', 'Default prover URLs per chain.', 'prover', `vec![${fallback}]`],
    ['default_eth_rpcs', 'Default Ethereum RPC URLs per chain.', 'eth_rpc', 'vec![]'],
    ['default_beacon_apis', 'Default beacon API URLs per chain.', 'beacon_api', 'vec![]'],
    ['default_checkpointz', 'Default checkpointz URLs per chain.', 'checkpointz', 'vec![]'],
  ];

  for (const [fn, doc, field, fallbackExpr] of fns) {
    out += `/// ${doc}\n`;
    out += `pub fn ${fn}(chain_id: u64) -> Vec<String> {\n`;
    out += '    match chain_id {\n';
    for (const chain of spec.chains) {
      out += `        ${RUST_CONST[chain.id]} => ${rustVec(chain[field])},\n`;
    }
    out += `        _ => ${fallbackExpr},\n`;
    out += '    }\n';
    out += '}\n\n';
  }

  out += '#[cfg(test)]\n';
  out += 'mod tests {\n';
  out += '    use super::*;\n\n';
  out += '    #[test]\n';
  out += '    fn known_chains_have_endpoints() {\n';
  out += `        for id in [${spec.chains.map((c) => RUST_CONST[c.id]).join(', ')}] {\n`;
  out += '            assert!(!default_provers(id).is_empty());\n';
  out += '            assert!(!default_eth_rpcs(id).is_empty());\n';
  out += '            assert!(!default_beacon_apis(id).is_empty());\n';
  out += '            assert!(!default_checkpointz(id).is_empty());\n';
  out += '        }\n';
  out += '    }\n\n';
  out += '    #[test]\n';
  out += '    fn cloudflare_prover_first_and_direct_lb_second() {\n';
  out += '        let mainnet = default_provers(MAINNET);\n';
  out += '        assert_eq!(mainnet[0], "https://mainnet.colibri-proof.tech");\n';
  out += '        assert_eq!(mainnet[1], "https://mainnet1.colibri-proof.tech");\n';
  out += '        let sepolia = default_provers(SEPOLIA);\n';
  out += '        assert_eq!(sepolia[0], "https://sepolia.colibri-proof.tech");\n';
  out += '        assert_eq!(sepolia[1], "https://sepolia1.colibri-proof.tech");\n';
  out += '        let gnosis = default_provers(GNOSIS);\n';
  out += '        assert_eq!(gnosis[0], "https://gnosis.colibri-proof.tech");\n';
  out += '        assert_eq!(gnosis[1], "https://gnosis1.colibri-proof.tech");\n';
  out += '    }\n\n';
  out += '    #[test]\n';
  out += '    fn plataberget_defaults() {\n';
  out += '        assert_eq!(default_provers(PLATABERGET), vec!["https://plataberget.colibri-proof.tech"]);\n';
  out += '        assert!(default_eth_rpcs(PLATABERGET)[0].contains("/execution"));\n';
  out += '        assert!(default_beacon_apis(PLATABERGET)[0].contains("/consensus"));\n';
  out += '    }\n\n';
  out += '    #[test]\n';
  out += '    fn unknown_chain_has_prover_fallback_only() {\n';
  out += '        assert!(!default_provers(999999).is_empty());\n';
  out += '        assert!(default_eth_rpcs(999999).is_empty());\n';
  out += '        assert!(default_beacon_apis(999999).is_empty());\n';
  out += '        assert!(default_checkpointz(999999).is_empty());\n';
  out += '    }\n';
  out += '}\n';
  return out;
}

function dartList(urls) {
  if (urls.length === 0) return '<String>[]';
  if (urls.length === 1) return `[${JSON.stringify(urls[0])}]`;
  const inner = urls.map((u) => `        ${JSON.stringify(u)},`).join('\n');
  return `[\n${inner}\n      ]`;
}

function genDart(spec) {
  let out = banner('dart');
  out += '\n';
  for (const chain of spec.chains) {
    const name = chain.name.replace(/[^a-zA-Z0-9]/g, '');
    const ident = 'chain' + name.charAt(0).toUpperCase() + name.slice(1);
    out += `/// ${chain.name} chain ID.\n`;
    out += `const int ${ident} = ${chain.id};\n`;
  }
  out += '\n';

  const fallback = spec.unknown_chain_prover_fallback.map((u) => JSON.stringify(u)).join(', ');
  const fns = [
    ['defaultProvers', 'Default prover endpoints by chain.', 'prover', `[${fallback}]`],
    ['defaultEthRpcs', 'Default execution RPC endpoints by chain.', 'eth_rpc', '<String>[]'],
    ['defaultBeaconApis', 'Default beacon API endpoints by chain.', 'beacon_api', '<String>[]'],
    ['defaultCheckpointz', 'Default checkpointz endpoints by chain.', 'checkpointz', '<String>[]'],
  ];

  for (const [fn, doc, field, fallbackExpr] of fns) {
    out += `/// ${doc}\n`;
    out += `List<String> ${fn}(int chainId) {\n`;
    out += '  return switch (chainId) {\n';
    for (const chain of spec.chains) {
      out += `    ${chain.id} => ${dartList(chain[field])},\n`;
    }
    out += `    _ => ${fallbackExpr},\n`;
    out += '  };\n';
    out += '}\n\n';
  }
  return out;
}

function ktChainId(id) {
  if (id === 1) return 'BigInteger.ONE';
  if (id > 2147483647) return `BigInteger("${id}")`;
  return `BigInteger.valueOf(${id}L)`;
}

function ktArray(urls) {
  if (urls.length === 0) return 'emptyArray()';
  if (urls.length === 1) return `arrayOf(${JSON.stringify(urls[0])})`;
  const inner = urls.map((u) => `                ${JSON.stringify(u)},`).join('\n');
  return `arrayOf(\n${inner}\n            )`;
}

function genKt(spec) {
  let out = banner('kt');
  out += 'package com.corpuscore.colibri\n\n';
  out += 'import java.math.BigInteger\n\n';
  out += '/** Default chain endpoint tables. Generated -- do not edit. */\n';
  out += 'object DefaultChains {\n';

  const fallback = spec.unknown_chain_prover_fallback.map((u) => JSON.stringify(u)).join(', ');
  const fns = [
    ['defaultProvers', 'Default prover URLs for supported chains.', 'prover', `arrayOf(${fallback})`],
    ['defaultEthRpcs', 'Default Ethereum RPC URLs for supported chains.', 'eth_rpc', 'emptyArray()'],
    ['defaultBeaconApis', 'Default beacon API URLs for supported chains.', 'beacon_api', 'emptyArray()'],
    ['defaultCheckpointz', 'Default checkpointz URLs for supported chains.', 'checkpointz', 'emptyArray()'],
  ];

  for (const [fn, doc, field, fallbackExpr] of fns) {
    out += `    /** ${doc} */\n`;
    out += `    @JvmStatic\n`;
    out += `    fun ${fn}(chainId: BigInteger): Array<String> = when (chainId) {\n`;
    for (const chain of spec.chains) {
      out += `        ${ktChainId(chain.id)} -> ${ktArray(chain[field])}\n`;
    }
    out += `        else -> ${fallbackExpr}\n`;
    out += '    }\n\n';
  }
  out += '}\n';
  return out;
}

function swiftArray(urls) {
  if (urls.length === 0) return '[]';
  if (urls.length === 1) return `[${JSON.stringify(urls[0])}]`;
  const inner = urls.map((u) => `                ${JSON.stringify(u)},`).join('\n');
  return `[\n${inner}\n            ]`;
}

function genSwift(spec) {
  let out = banner('swift');
  out += '\n';
  out += '/// Default chain endpoint tables. Generated -- do not edit.\n';
  out += 'enum DefaultChains {\n';

  const fallback = spec.unknown_chain_prover_fallback.map((u) => JSON.stringify(u)).join(', ');
  const fns = [
    ['defaultProvers', 'Default prover URLs for supported chains.', 'prover', `[${fallback}]`],
    ['defaultEthRpcs', 'Default Ethereum RPC URLs for supported chains.', 'eth_rpc', '[]'],
    ['defaultBeaconApis', 'Default beacon API URLs for supported chains.', 'beacon_api', '[]'],
    ['defaultCheckpointz', 'Default checkpointz URLs for supported chains.', 'checkpointz', '[]'],
  ];

  for (const [fn, doc, field, fallbackExpr] of fns) {
    out += `    /// ${doc}\n`;
    out += `    static func ${fn}(for chainId: UInt64) -> [String] {\n`;
    out += '        switch chainId {\n';
    for (const chain of spec.chains) {
      out += `        case ${chain.id}:\n`;
      out += `            return ${swiftArray(chain[field])}\n`;
    }
    out += '        default:\n';
    out += `            return ${fallbackExpr}\n`;
    out += '        }\n';
    out += '    }\n\n';
  }
  out += '}\n';
  return out;
}

const OUTPUTS = [
  { rel: 'src/cli/default_chains.generated.h', gen: genC },
  { rel: 'bindings/emscripten/src/chains.generated.ts', gen: genTs },
  { rel: 'bindings/python/src/colibri/default_chains.py', gen: genPy },
  { rel: 'bindings/rust/src/types/chain.rs', gen: genRs },
  { rel: 'bindings/dart/lib/src/default_chains.dart', gen: genDart },
  { rel: 'bindings/kotlin/lib/src/main/kotlin/com/corpuscore/colibri/DefaultChains.kt', gen: genKt },
  { rel: 'bindings/swift/Sources/Colibri/DefaultChains.swift', gen: genSwift },
];

function main() {
  const spec = loadSpec();
  let drifted = false;
  for (const { rel, gen } of OUTPUTS) {
    const abs = path.join(ROOT, rel);
    const content = gen(spec);
    const existing = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : null;
    if (CHECK) {
      if (existing !== content) {
        console.error(`Out of date: ${rel}`);
        drifted = true;
      }
      continue;
    }
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, content);
    console.log(`Wrote ${rel}`);
  }
  if (CHECK) {
    if (drifted) {
      console.error('Run: node scripts/chain_defaults/generate.js');
      process.exit(1);
    }
    console.log('Generated chain defaults are up to date.');
  }
}

main();
