//! Generated by `scripts/chain_defaults/generate.js` -- do not edit.
//!
//! Chain identifiers and default endpoint URLs.

/// Ethereum Mainnet.
pub const MAINNET: u64 = 1;
/// Ethereum Sepolia testnet.
pub const SEPOLIA: u64 = 11_155_111;
/// Gnosis Chain.
pub const GNOSIS: u64 = 100;
/// Chiado testnet (Gnosis).
pub const CHIADO: u64 = 10_200;
/// Platåberget (Glamsterdam devnet-8).
pub const PLATABERGET: u64 = 7_091_047_534;

/// Default prover URLs per chain.
pub fn default_provers(chain_id: u64) -> Vec<String> {
    match chain_id {
        MAINNET => vec![
            "https://mainnet.colibri-proof.tech".into(),
            "https://mainnet1.colibri-proof.tech".into(),
            "https://mainnet-prover.incubed.net".into(),
            "https://mainnet.colimind.com".into(),
        ],
        SEPOLIA => vec![
            "https://sepolia.colibri-proof.tech".into(),
            "https://sepolia1.colibri-proof.tech".into(),
        ],
        GNOSIS => vec![
            "https://gnosis.colibri-proof.tech".into(),
            "https://gnosis1.colibri-proof.tech".into(),
        ],
        CHIADO => vec!["https://chiado.colibri-proof.tech".into()],
        PLATABERGET => vec!["https://plataberget.colibri-proof.tech".into()],
        _ => vec!["https://c4.incubed.net".into()],
    }
}

/// Default Ethereum RPC URLs per chain.
pub fn default_eth_rpcs(chain_id: u64) -> Vec<String> {
    match chain_id {
        MAINNET => vec![
            "https://mainnet.colibri-proof.tech/execution".into(),
            "https://eth.drpc.org".into(),
            "https://ethereum-rpc.publicnode.com".into(),
            "https://singapore.rpc.blxrbdn.com".into(),
        ],
        SEPOLIA => vec![
            "https://sepolia.colibri-proof.tech/execution".into(),
            "https://ethereum-sepolia-rpc.publicnode.com".into(),
            "https://sepolia.gateway.tenderly.co".into(),
        ],
        GNOSIS => vec![
            "https://gnosis.colibri-proof.tech/execution".into(),
            "https://rpc.gnosischain.com".into(),
            "https://rpc.gnosis.gateway.fm".into(),
            "https://gnosis-rpc.publicnode.com".into(),
        ],
        CHIADO => vec![
            "https://rpc.chiado.gnosis.gateway.fm".into(),
            "https://rpc.chiadochain.net".into(),
            "https://gnosis-chiado-rpc.publicnode.com".into(),
        ],
        PLATABERGET => vec!["https://plataberget.colibri-proof.tech/execution".into()],
        _ => vec![],
    }
}

/// Default beacon API URLs per chain.
pub fn default_beacon_apis(chain_id: u64) -> Vec<String> {
    match chain_id {
        MAINNET => vec![
            "https://mainnet.colibri-proof.tech/consensus".into(),
            "https://gateway.tenderly.co/public/mainnet".into(),
            "https://ethereum-beacon-api.publicnode.com".into(),
        ],
        SEPOLIA => vec![
            "https://sepolia.colibri-proof.tech/consensus".into(),
            "https://ethereum-sepolia-beacon-api.publicnode.com".into(),
        ],
        GNOSIS => vec![
            "https://gnosis.colibri-proof.tech/consensus".into(),
            "https://rpc-gbc.gnosischain.com".into(),
            "https://gnosis-beacon-api.publicnode.com".into(),
        ],
        CHIADO => vec!["https://rpc-gbc.chiadochain.net".into()],
        PLATABERGET => vec!["https://plataberget.colibri-proof.tech/consensus".into()],
        _ => vec![],
    }
}

/// Default checkpointz URLs per chain.
pub fn default_checkpointz(chain_id: u64) -> Vec<String> {
    match chain_id {
        MAINNET => vec![
            "https://sync-mainnet.beaconcha.in".into(),
            "https://mainnet.checkpoint.sigp.io".into(),
            "https://mainnet-checkpoint-sync.attestant.io".into(),
            "https://beaconstate-mainnet.chainsafe.io".into(),
            "https://mainnet-checkpoint-sync.stakely.io".into(),
            "https://checkpointz.pietjepuk.net".into(),
            "https://beaconstate.ethstaker.cc".into(),
        ],
        SEPOLIA => vec![
            "https://checkpoint-sync.sepolia.ethpandaops.io".into(),
            "https://beaconstate-sepolia.chainsafe.io".into(),
        ],
        GNOSIS => vec!["https://checkpoint.gnosischain.com".into()],
        CHIADO => vec!["https://checkpoint.chiadochain.net".into()],
        PLATABERGET => vec!["https://checkpoint-sync.glamsterdam-devnet-8.ethpandaops.io".into()],
        _ => vec![],
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn known_chains_have_endpoints() {
        for id in [MAINNET, SEPOLIA, GNOSIS, CHIADO, PLATABERGET] {
            assert!(!default_provers(id).is_empty());
            assert!(!default_eth_rpcs(id).is_empty());
            assert!(!default_beacon_apis(id).is_empty());
            assert!(!default_checkpointz(id).is_empty());
        }
    }

    #[test]
    fn cloudflare_prover_first_and_direct_lb_second() {
        let mainnet = default_provers(MAINNET);
        assert_eq!(mainnet[0], "https://mainnet.colibri-proof.tech");
        assert_eq!(mainnet[1], "https://mainnet1.colibri-proof.tech");
        let sepolia = default_provers(SEPOLIA);
        assert_eq!(sepolia[0], "https://sepolia.colibri-proof.tech");
        assert_eq!(sepolia[1], "https://sepolia1.colibri-proof.tech");
        let gnosis = default_provers(GNOSIS);
        assert_eq!(gnosis[0], "https://gnosis.colibri-proof.tech");
        assert_eq!(gnosis[1], "https://gnosis1.colibri-proof.tech");
    }

    #[test]
    fn plataberget_defaults() {
        assert_eq!(default_provers(PLATABERGET), vec!["https://plataberget.colibri-proof.tech"]);
        assert!(default_eth_rpcs(PLATABERGET)[0].contains("/execution"));
        assert!(default_beacon_apis(PLATABERGET)[0].contains("/consensus"));
    }

    #[test]
    fn unknown_chain_has_prover_fallback_only() {
        assert!(!default_provers(999999).is_empty());
        assert!(default_eth_rpcs(999999).is_empty());
        assert!(default_beacon_apis(999999).is_empty());
        assert!(default_checkpointz(999999).is_empty());
    }
}
