name: colibri_flutter
description: Flutter wrapper for Colibri Stateless (Dart FFI).
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  colibri_stateless:
    path: ../../dart

flutter:
  plugin:
    platforms:
      android:
        package: com.corpuscore.colibri_flutter
        pluginClass: ColibriFlutterPlugin
      ios:
        pluginClass: ColibriFlutterPlugin
