/*
 * Copyright (c) 2025 corpus.core
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * SPDX-License-Identifier: MIT
 */

#ifndef verify_h__
#define verify_h__

#ifdef __cplusplus
extern "C" {
#endif

#define RPC_METHOD(name, data, proof) name
#include "../util/bytes.h"
#include "../util/chains.h"
#include "../util/crypto.h"
#include "../util/json.h"
#include "../util/ssz.h"
#include "../util/state.h"
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>

// : APIs

// :: Internal APIs
//
// This header should be used only if you implement new verifiers or need direct access.
// The internal APIs are not guaranteed to be stable and can be changed or removed without prior notice.

// ::: verify.h
// The verifier API executes a proof verification.
// when calling c4_verify_from_bytes, c4_verify needs to be called until the status is either C4_ERROR or C4_SUCCESS.
//
// Example:
//
// ```c
//  verify_ctx_t ctx = {0};
//  for (
//      c4_status_t status = c4_verify_from_bytes(&ctx, request_bytes, method, json_parse(args), chain_id);
//      status == C4_PENDING;
//      status = c4_verify(&ctx))
//      curl_fetch_all(&ctx.state);
//  if (ctx.success) {
//    ssz_dump_to_file_no_quotes(stdout, ctx.data);
//    return EXIT_SUCCESS;
//  }
//  else if (ctx.state.error) {
//    fprintf(stderr, "proof is invalid: %s\n", ctx.state.error);
//    return EXIT_FAILURE;
//  }
// ```
//

/**
 * a bitmask holding flags used during the verification context.
 */
typedef uint32_t verify_flags_t;

/**
 * a enum as list of flags used during the verification context.
 */
typedef enum {
  VERIFY_FLAG_FREE_DATA      = 1 << 0, // if set, the data section will be freed after verification. This flag is set when the verifier generates the actual result data from the proof and needs cleanup afterwards.
  VERIFY_FLAG_PAP            = 1 << 1, // if set, Pragmatic Adaptive Privacy mode is active. The verifier may use cached storage values for optimistic execution and verify them afterwards.
  VERIFY_FLAG_REMOTE_PROVER  = 1 << 2, // if set, a remote prover server is available. The verifier may emit C4_DATA_TYPE_PROVER requests (e.g. fetch tx_cache, request block proofs).
  VERIFY_FLAG_PROOF_ONLY     = 1 << 3, // if set, the verifier will only return the proof and not the data.
  VERIFY_FLAG_HYBRID         = 1 << 4, // SECURITY: only safe when proof was generated by local hybrid prover that already verified the header
  VERIFY_FLAG_REVERTED       = 1 << 5, // set by the verifier when an `eth_call` / `eth_estimateGas` was successfully verified but the underlying EVM execution reverted. The revert data is exposed via `verify_ctx_t.data` (raw `bytes` SSZ type). Bindings/hosts should surface this as a structured error (e.g. JSON-RPC code 3) so callers like ethers can decode `OffchainLookup` (EIP-3668 / CCIP-Read) reverts.
  VERIFY_FLAG_OBLIVIOUS      = 1 << 6, // if set, the verifier will use the oblivious_node
  VERIFY_FLAG_SKIP_WSP_CHECK = 1 << 7, // if set, skip the Weak Subjectivity Period check for prover-provided or fetched sync committee data. SECURITY: Only use when an alternative trust anchor (witness signatures, hard-coded checkpoint, signed package) is available. Disabling increases the risk of long-range attacks when syncing across periods older than the WSP.
} verify_flag_t;

/**
 * a struct holding the verification context.
 */
typedef struct {
  char*          method;              // the rpc-method
  json_t         args;                // the rpc-args as json array
  ssz_ob_t       proof;               // the proof as ssz object using the Proof-Type directly
  ssz_ob_t       data;                // the data as ssz object or Empty if not needed
  ssz_ob_t       sync_data;           // the sync-data as ssz object or Empty if not needed
  bool           success;             // true if the verification was successful
  c4_state_t     state;               // the state of the verification holding errors or data requests.
  chain_id_t     chain_id;            // the chain-id of the verification
  bytes_t        witness_keys;        // the witness keys used to sign the checkpoints (multiple addresses are concatinated bytes with 20 bytes each)
  verify_flags_t flags;               // a bitmask holding flags used during the verification context.
  uint64_t       min_latest_block_ts; // Lower bound for `block.timestamp` (Unix seconds) used for freshness check.  `0` disables the check.
  void*          user_data;           // optional method-specific in-memory state surviving C4_PENDING rounds
  void (*user_data_free)(void*);      // cleanup function called by c4_verify_free(); may be NULL
} verify_ctx_t;

/**
 * a enum as list of method types.
 */
typedef enum {
  METHOD_UNDEFINED     = 0, // the method is not defined
  METHOD_PROOFABLE     = 1, // the method is proofable
  METHOD_UNPROOFABLE   = 2, // the method is unproofable
  METHOD_NOT_SUPPORTED = 3, // the method is not supported
  METHOD_LOCAL         = 4  // the method is executed locally
} method_type_t;

/**
 * get the request type for a given chain-type.
 * For each chain-type there is one request-type used, the request-type will be specified by the verifier-module.
 */
const ssz_def_t* c4_get_request_type(chain_type_t chain_type);

/**
 * get the chain-type from a given request.
 *
 * The chain-type is based on the first byte of the request, which corresponds
 * to the chain_type_t enum value.
 * @param request_bytes the request bytes to analyze
 * @return the chain type, defaults to C4_CHAIN_TYPE_ETHEREUM for invalid requests
 */
chain_type_t c4_get_chain_type_from_req(bytes_t request_bytes);

/**
 * get the request type from a given request.
 *
 * The request-type is based on the chain type extracted from the request.
 * @param request_bytes the request bytes to analyze
 * @return the SSZ definition for the request type
 */
const ssz_def_t* c4_get_req_type_from_req(bytes_t request_bytes);

/**
 * the main verification function executing the verifier in the modules.
 * @param ctx the verification context
 * @return C4_SUCCESS, C4_ERROR, or C4_PENDING
 */
c4_status_t c4_verify(verify_ctx_t* ctx);

/**
 * shortcut to verify a request from bytes.
 * @param ctx the verification context.
 * @param request_bytes the request as bytes.
 * @param method the method to verify (required, cannot be NULL).
 * @param args the arguments for the method as json array.
 * @param chain_id the chain-id of the request.
 * @return C4_SUCCESS, C4_ERROR, or C4_PENDING
 */
c4_status_t c4_verify_from_bytes(verify_ctx_t* ctx, bytes_t request_bytes, char* method, json_t args, chain_id_t chain_id);

/**
 * free all allocated memory from the verification context. it does not free the verification context itself.
 */
void c4_verify_free_data(verify_ctx_t* ctx);

/**
 * initialize the verification context.
 *
 * @param ctx the verification context (required, cannot be NULL).
 * @param request_bytes the request as bytes.
 * @param method the method to verify (required, cannot be NULL).
 * @param args the arguments for the method as json array.
 * @param chain_id the chain-id of the request.
 * @return C4_SUCCESS or C4_ERROR
 */
c4_status_t c4_verify_init(verify_ctx_t* ctx, bytes_t request_bytes, char* method, json_t args, chain_id_t chain_id, verify_flags_t flags);

/**
 * get the method type for a given chain-id, method, params and verify flags.
 *
 * The params are used in PAP mode to check whether cached data is available,
 * which may change the returned method type (e.g. PROOFABLE to LOCAL).
 * The flags (e.g. VERIFY_FLAG_PAP) must be passed because this function is
 * called before the verify context exists.
 *
 * @param chain_id the chain-id
 * @param method the rpc-method name
 * @param params the rpc-params as parsed json array (may be empty)
 * @param flags verify flags (e.g. VERIFY_FLAG_PAP for PAP mode)
 */
method_type_t c4_get_method_type(chain_id_t chain_id, char* method, json_t params, verify_flags_t flags);

/**
 * Transforms method and params for a remote prover request.
 *
 * Each chain module may rewrite the RPC method and parameters before they
 * are sent to the remote prover. For example, PAP mode may replace
 * `eth_call` with `eth_getProof` and adjust the params accordingly.
 * If no module transforms the payload, the output buffers remain empty
 * and the caller should use the original method/params.
 *
 * @param chain_id the chain-id
 * @param method the original rpc-method name
 * @param params the original rpc-params as JSON string
 * @param flags verify flags (e.g. VERIFY_FLAG_PAP)
 * @param method_out output buffer for the transformed method (empty if unchanged)
 * @param params_out output buffer for the transformed params (empty if unchanged)
 */
void c4_get_prover_payload(chain_id_t chain_id, const char* method, const char* params,
                           verify_flags_t flags, buffer_t* method_out, buffer_t* params_out);

/**
 * Helper context for chain-specific RPC initialization (`c4_init_rpc_ctx`).
 *
 * The caller (e.g. the bindings layer) populates `chain_id` and `client_state`
 * before invoking `c4_init_rpc_ctx`. Each registered chain hook may then
 * prepend `data_request_t` entries (typically `C4_DATA_TYPE_CACHE`) to the
 * `snapshots` list. Ownership of allocated entries transfers to the caller,
 * which is responsible for freeing them (or transferring ownership further).
 */
typedef struct {
  chain_id_t      chain_id;     ///< target chain
  bytes_t         client_state; ///< snapshot of `client_state` at request start (read-only)
  data_request_t* snapshots;    ///< output: linked list of cache snapshots (owned by caller after the call returns)
} c4_init_ctx_t;

/**
 * Dispatches to chain-specific RPC-context initialization hooks.
 *
 * Each chain module may register an `INIT_RPC_CTX` hook via CMake. Hooks
 * are invoked in registration order; they typically inspect `client_state`
 * to decide which cached data to snapshot and prepend matching entries to
 * `ctx->snapshots`. Hooks not relevant for the given `chain_id` simply
 * return without modifying `ctx`.
 *
 * @param ctx initialization context (must not be NULL)
 */
void c4_init_rpc_ctx(c4_init_ctx_t* ctx);

#pragma endregion
#ifdef MESSAGES
#define RETURN_VERIFY_ERROR(ctx, msg)     \
  do {                                    \
    c4_state_add_error(&ctx->state, msg); \
    ctx->success = false;                 \
    return false;                         \
  } while (0)
#define RETURN_VERIFY_ERROR_STATUS(ctx, msg) \
  do {                                       \
    c4_state_add_error(&ctx->state, msg);    \
    ctx->success = false;                    \
    return C4_ERROR;                         \
  } while (0)
#else
#define RETURN_VERIFY_ERROR(ctx, msg) \
  do {                                \
    ctx->state.error = "E";           \
    return false;                     \
  } while (0)
#define RETURN_VERIFY_ERROR_STATUS(ctx, msg) \
  do {                                       \
    ctx->state.error = "E";                  \
    return C4_ERROR;                         \
  } while (0)
#endif

#ifdef __cplusplus
}
#endif

#endif