// Generated by scripts/chain_defaults/generate.js -- do not edit.
package com.corpuscore.colibri

import java.math.BigInteger

/** Default chain endpoint tables. Generated -- do not edit. */
object DefaultChains {
    /** Default prover URLs for supported chains. */
    @JvmStatic
    fun defaultProvers(chainId: BigInteger): Array<String> = when (chainId) {
        BigInteger.ONE -> arrayOf(
                "https://mainnet.colibri-proof.tech",
                "https://mainnet1.colibri-proof.tech",
                "https://mainnet-prover.incubed.net",
                "https://mainnet.colimind.com",
            )
        BigInteger.valueOf(11155111L) -> arrayOf(
                "https://sepolia.colibri-proof.tech",
                "https://sepolia1.colibri-proof.tech",
            )
        BigInteger.valueOf(100L) -> arrayOf(
                "https://gnosis.colibri-proof.tech",
                "https://gnosis1.colibri-proof.tech",
            )
        BigInteger.valueOf(10200L) -> arrayOf("https://chiado.colibri-proof.tech")
        BigInteger("7091047534") -> arrayOf("https://plataberget.colibri-proof.tech")
        else -> arrayOf("https://c4.incubed.net")
    }

    /** Default Ethereum RPC URLs for supported chains. */
    @JvmStatic
    fun defaultEthRpcs(chainId: BigInteger): Array<String> = when (chainId) {
        BigInteger.ONE -> arrayOf(
                "https://mainnet.colibri-proof.tech/execution",
                "https://eth.drpc.org",
                "https://ethereum-rpc.publicnode.com",
                "https://singapore.rpc.blxrbdn.com",
            )
        BigInteger.valueOf(11155111L) -> arrayOf(
                "https://sepolia.colibri-proof.tech/execution",
                "https://ethereum-sepolia-rpc.publicnode.com",
                "https://sepolia.gateway.tenderly.co",
            )
        BigInteger.valueOf(100L) -> arrayOf(
                "https://gnosis.colibri-proof.tech/execution",
                "https://rpc.gnosischain.com",
                "https://rpc.gnosis.gateway.fm",
                "https://gnosis-rpc.publicnode.com",
            )
        BigInteger.valueOf(10200L) -> arrayOf(
                "https://rpc.chiado.gnosis.gateway.fm",
                "https://rpc.chiadochain.net",
                "https://gnosis-chiado-rpc.publicnode.com",
            )
        BigInteger("7091047534") -> arrayOf("https://plataberget.colibri-proof.tech/execution")
        else -> emptyArray()
    }

    /** Default beacon API URLs for supported chains. */
    @JvmStatic
    fun defaultBeaconApis(chainId: BigInteger): Array<String> = when (chainId) {
        BigInteger.ONE -> arrayOf(
                "https://mainnet.colibri-proof.tech/consensus",
                "https://gateway.tenderly.co/public/mainnet",
                "https://ethereum-beacon-api.publicnode.com",
            )
        BigInteger.valueOf(11155111L) -> arrayOf(
                "https://sepolia.colibri-proof.tech/consensus",
                "https://ethereum-sepolia-beacon-api.publicnode.com",
            )
        BigInteger.valueOf(100L) -> arrayOf(
                "https://gnosis.colibri-proof.tech/consensus",
                "https://rpc-gbc.gnosischain.com",
                "https://gnosis-beacon-api.publicnode.com",
            )
        BigInteger.valueOf(10200L) -> arrayOf("https://rpc-gbc.chiadochain.net")
        BigInteger("7091047534") -> arrayOf("https://plataberget.colibri-proof.tech/consensus")
        else -> emptyArray()
    }

    /** Default checkpointz URLs for supported chains. */
    @JvmStatic
    fun defaultCheckpointz(chainId: BigInteger): Array<String> = when (chainId) {
        BigInteger.ONE -> arrayOf(
                "https://sync-mainnet.beaconcha.in",
                "https://mainnet.checkpoint.sigp.io",
                "https://mainnet-checkpoint-sync.attestant.io",
                "https://beaconstate-mainnet.chainsafe.io",
                "https://mainnet-checkpoint-sync.stakely.io",
                "https://checkpointz.pietjepuk.net",
                "https://beaconstate.ethstaker.cc",
            )
        BigInteger.valueOf(11155111L) -> arrayOf(
                "https://checkpoint-sync.sepolia.ethpandaops.io",
                "https://beaconstate-sepolia.chainsafe.io",
            )
        BigInteger.valueOf(100L) -> arrayOf("https://checkpoint.gnosischain.com")
        BigInteger.valueOf(10200L) -> arrayOf("https://checkpoint.chiadochain.net")
        BigInteger("7091047534") -> arrayOf("https://checkpoint-sync.glamsterdam-devnet-8.ethpandaops.io")
        else -> emptyArray()
    }

}
