// Generated by CMake. Do not edit manually.
// Provides the absolute path to the Emscripten build output directory.
export const emscriptenBuildDir = "/Users/steffenkux/development/working/corpus.core/colibri-stateless/build/wasm-debug/emscripten"; 
