// Generated by scripts/chain_defaults/generate.js -- do not edit.

/// mainnet chain ID.
const int chainMainnet = 1;
/// sepolia chain ID.
const int chainSepolia = 11155111;
/// gnosis chain ID.
const int chainGnosis = 100;
/// chiado chain ID.
const int chainChiado = 10200;
/// plataberget chain ID.
const int chainPlataberget = 7091047534;

/// Default prover endpoints by chain.
List<String> defaultProvers(int chainId) {
  return switch (chainId) {
    1 => [
        "https://mainnet.colibri-proof.tech",
        "https://mainnet1.colibri-proof.tech",
        "https://mainnet-prover.incubed.net",
        "https://mainnet.colimind.com",
      ],
    11155111 => [
        "https://sepolia.colibri-proof.tech",
        "https://sepolia1.colibri-proof.tech",
      ],
    100 => [
        "https://gnosis.colibri-proof.tech",
        "https://gnosis1.colibri-proof.tech",
      ],
    10200 => ["https://chiado.colibri-proof.tech"],
    7091047534 => ["https://plataberget.colibri-proof.tech"],
    _ => ["https://c4.incubed.net"],
  };
}

/// Default execution RPC endpoints by chain.
List<String> defaultEthRpcs(int chainId) {
  return switch (chainId) {
    1 => [
        "https://mainnet.colibri-proof.tech/execution",
        "https://eth.drpc.org",
        "https://ethereum-rpc.publicnode.com",
        "https://singapore.rpc.blxrbdn.com",
      ],
    11155111 => [
        "https://sepolia.colibri-proof.tech/execution",
        "https://ethereum-sepolia-rpc.publicnode.com",
        "https://sepolia.gateway.tenderly.co",
      ],
    100 => [
        "https://gnosis.colibri-proof.tech/execution",
        "https://rpc.gnosischain.com",
        "https://rpc.gnosis.gateway.fm",
        "https://gnosis-rpc.publicnode.com",
      ],
    10200 => [
        "https://rpc.chiado.gnosis.gateway.fm",
        "https://rpc.chiadochain.net",
        "https://gnosis-chiado-rpc.publicnode.com",
      ],
    7091047534 => [
        "https://plataberget.colibri-proof.tech/execution",
        "https://rpc.glamsterdam-devnet-8.ethpandaops.io/",
      ],
    _ => <String>[],
  };
}

/// Default beacon API endpoints by chain.
List<String> defaultBeaconApis(int chainId) {
  return switch (chainId) {
    1 => [
        "https://mainnet.colibri-proof.tech/consensus",
        "https://gateway.tenderly.co/public/mainnet",
        "https://ethereum-beacon-api.publicnode.com",
      ],
    11155111 => [
        "https://sepolia.colibri-proof.tech/consensus",
        "https://ethereum-sepolia-beacon-api.publicnode.com",
      ],
    100 => [
        "https://gnosis.colibri-proof.tech/consensus",
        "https://rpc-gbc.gnosischain.com",
        "https://gnosis-beacon-api.publicnode.com",
      ],
    10200 => ["https://rpc-gbc.chiadochain.net"],
    7091047534 => [
        "https://plataberget.colibri-proof.tech/consensus",
        "https://beacon.glamsterdam-devnet-8.ethpandaops.io/",
      ],
    _ => <String>[],
  };
}

/// Default checkpointz endpoints by chain.
List<String> defaultCheckpointz(int chainId) {
  return switch (chainId) {
    1 => [
        "https://sync-mainnet.beaconcha.in",
        "https://mainnet.checkpoint.sigp.io",
        "https://mainnet-checkpoint-sync.attestant.io",
        "https://beaconstate-mainnet.chainsafe.io",
        "https://mainnet-checkpoint-sync.stakely.io",
        "https://checkpointz.pietjepuk.net",
        "https://beaconstate.ethstaker.cc",
      ],
    11155111 => [
        "https://checkpoint-sync.sepolia.ethpandaops.io",
        "https://beaconstate-sepolia.chainsafe.io",
      ],
    100 => ["https://checkpoint.gnosischain.com"],
    10200 => ["https://checkpoint.chiadochain.net"],
    7091047534 => ["https://checkpoint-sync.glamsterdam-devnet-8.ethpandaops.io"],
    _ => <String>[],
  };
}

